return {
    Structs = {

        UnknownAbilityDefArray = {
            name = "UnknownAbilityDefArray",
            fields = {
                { name = "unknown1", type = "int32" },
                { name = "unknown2", type = "int32" },
                { name = "unknown3", type = "int32" },
                { name = "ability_id", type = "int32" },
                { name = "unknown5", type = "int32" },
                { name = "unknown6", type = "int32" }, -- Always 100
                { name = "unknown7", type = "bool" },
                { name = "unknown8", type = "int32" },
                { name = "unknown9", type = "int32" },
                { name = "unknown10", type = "float" },
                { name = "unknown11", type = "float" },
                { name = "unknown12", type = "float" },
                { name = "unknown13", type = "int32" },
                { name = "unknown14", type = "int32" },
                { name = "unknown15", type = "int32" },
                { name = "unknown16", type = "int32" },
                { name = "unknown17", type = "int32" },
                { name = "unknown18", type = "int32" },
                { name = "unknown19", type = "bool" },
                { name = "unknown20", type = "bool" },
                { name = "unknown21", type = "string32" },
                { name = "unknown22", type = "float" }, -- unknown22 and unknown25 always seem to match - possibly some kind of millis?
                { name = "unknown23", type = "float" },
                { name = "unknown24", type = "float" },
                { name = "unknown25", type = "float" },
                { name = "unknown26", type = "float" },
                { name = "unknown27", type = "float" },
                { name = "unknown28", type = "int32" }, -- Commonly has string id 2823 "Deals #number([*Param1TunedLow*]) damage."
                { name = "unknown29", type = "int32" },
                { name = "unknown30", type = "int32" },
                { name = "unknown31", type = "float" },
                { name = "unknown32", type = "int32" },
                { name = "unknown33", type = "int32" },
                { name = "unknown34", type = "int32" },
                { name = "unknown35", type = "int32" },
                { name = "unknown36", type = "int32" },
                { name = "unknown37", type = "int32" },
                { name = "unknown38", type = "int32" },
                { name = "unknown39", type = "int32" },
                { name = "unknown40", type = "bool" },
                { name = "unknown41", type = "float" },
                { name = "unknown42", type = "float" },
                { name = "unknown43", type = "float" },
                { name = "unknown44", type = "bool" },
                { name = "unknown45", type = "int32" },
                { name = "unknown46", type = "bool" },
            },
        },
    },

    SubOpcodes = {
        [0x01] = { name = "AbilityPacketFailed" },
        [0x03] = { name = "AbilityPacketStartCasting" },
        [0x04] = {
            name = "AbilityPacketLaunchAndLand",
            fields = {
                { name = "launcher_guid", type = "uint64" },
                { name = "target1", type = "array", elem = "Target" },
                { name = "unknown1", type = "int32" },
                { name = "unknown2", type = "int32" },
                { name = "launcher_animation_id", type = "int32" },
                { name = "launcher_composite_effect", type = "int32" },
                { name = "unknown5", type = "int32" },
                { name = "unknown6", type = "bool" },
                { name = "unknown7", type = "bool" },
                { name = "landed_animation_id", type = "int32" },
                { name = "landed_composite_effect1", type = "int32" },
                { name = "unknown10", type = "int32" },
                { name = "unknown11", type = "Pos" },
                { name = "launcher_composite_effect_duration", type = "float" },
                { name = "unknown13", type = "float" },
                { name = "unknown14", type = "int32" },
                { name = "unknown15", type = "int32" },
                { name = "unknown16", type = "int32" },
                { name = "unknown17", type = "int32" },
                { name = "override_launcher_guid", type = "uint64" },
                { name = "track_target", type = "bool" },
                { name = "unknown20", type = "int32" },
                { name = "unknown21", type = "int32" },
                { name = "progressive_start_speed", type = "float" },
                { name = "progressive_end_speed", type = "float" },
                { name = "unknown24", type = "int32" },
                { name = "unknown25", type = "int32" },
                { name = "unknown26", type = "Pos" },
                { name = "unknown27", type = "Pos" },
                { name = "projectile_adr_name", type = "string32" },
                { name = "projectile_bone_source", type = "Target" },
                { name = "target3", type = "Target" },
                { name = "unknown29", type = "Pos" },
                { name = "unknown30", type = "float" },
                { name = "unknown31", type = "bool" },
                { name = "projectile_size", type = "float" },
                { name = "progressive_inflation_size", type = "float" },
                { name = "trail_composite_effect", type = "int32" },
                { name = "landed_composite_effect2", type = "int32" },
                { name = "unknown36", type = "int32" },
                { name = "unknown37", type = "int32" },
                { name = "unknown38", type = "float" },
                { name = "projectile_duration_seconds", type = "float" },
                { name = "unknown40", type = "float" },
                { name = "unknown41", type = "float" },
                { name = "unknown42", type = "float" },
                { name = "unknown43", type = "float" },
                { name = "unknown44", type = "float" },
                { name = "unknown45", type = "float" },
                { name = "unknown46", type = "string32" },
                { name = "unknown47", type = "int32" },
            },
        },
        [0x05] = { name = "AbilityPacketSetDefinition" },
        [0x06] = { name = "AbilityPacketClientMoveAndCast" },
        [0x07] = { name = "AbilityPacketPurchaseAbility" },
        [0x08] = { name = "AbilityPacketUpdateAbilityExperience" },
        [0x09] = { name = "AbilityPacketStopAura" },
        [0x0A] = { name = "AbilityPacketClientRequestStartAbility" },
        [0x0B] = { name = "AbilityPacketMeleeRefresh" },
        [0x0C] = { name = "AbilityPacketRequestAbilityDefinition" },

        [0x0D] = {
            name = "AbilityPacketAbilityDefinition",
            fields = {
                { name = "ability_id", type = "int32" },
                { name = "unknown2", type = "bool" }, -- Always true?
                { name = "unknown3", type = "bool" },
                { name = "name", type = "int32" },
                { name = "description", type = "int32" },
                { name = "unknown6", type = "int32" },
                { name = "unknown7", type = "float" },
                { name = "unknown8", type = "int32" },
                { name = "destination_land_composite_effect", type = "int32" }, -- Uncomfirmed
                { name = "target_land_composite_effect", type = "int32" }, -- Uncomfirmed
                { name = "unknown11", type = "int32" },
                { name = "cast_animation", type = "int32" },
                { name = "land_animation", type = "int32" },
                { name = "unknown14", type = "int32" },
                { name = "unknown15", type = "int32" },
                { name = "unknown16", type = "int32" },
                { name = "unknown17", type = "float" },
                { name = "unknown18", type = "float" },
                { name = "unknown19", type = "int32" },
                { name = "unknown20", type = "int32" },
                { name = "unknown21", type = "int32" },
                { name = "unknown22", type = "bool" },
                { name = "unknown23", type = "int32" },
                { name = "unknown24", type = "int32" },
                { name = "unknown25", type = "int32" },
                { name = "unknown26", type = "float" },
                { name = "trail_composite_effect", type = "int32" },
                { name = "description2", type = "int32" },
                { name = "unknown29", type = "float" },
                { name = "unknown30", type = "float" },
                { name = "unknown31", type = "int32" },
                { name = "unknown32", type = "int32" },
                { name = "unknown33", type = "int32" },
                { name = "unknown34", type = "float" },
                { name = "unknown35", type = "float" },
                { name = "unknown36", type = "bool" },
                { name = "unknown37", type = "int32" },
                { name = "unknown38", type = "int32" },
                { name = "unknown39", type = "bool" },
                { name = "unknown40", type = "bool" },
                { name = "unknown41", type = "bool" },
                { name = "unknown42", type = "int32" },
                { name = "unknown43", type = "float" },
                {
                    name = "unknown44",
                    type = "array",
                    elem = "UnknownAbilityDefArray",
                },
            },
        },

        [0x0E] = { name = "AbilityPacketDetonateProjectile" },
        [0x0F] = { name = "AbilityPacketPulseLocationTargeting" },
        [0x10] = { name = "AbilityPacketReceivePulseLocation" },
        [0x11] = { name = "AbilityPacketExecuteClientLua" },
        [0x12] = { name = "AbilityPacketCastInterrupt" },
    },
}
